export interface ProductVariant {
  id: string;
  name: string; // e.g. "Size 12", "Size 14", "9.5 Inches"
  inStock: boolean;
  stockQty?: number; // Per-size inventory quantity
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  category: "chain" | "anklet" | "ring" | "bracelet";
  categoryLabel: "Chain" | "Anklet" | "Ring" | "Bracelet";
  collection: "silver" | "artificial";
  pricingType: "fixed" | "weight_based";
  fixedPrice?: number;
  weightGrams?: number;
  makingCharge?: number;
  purity?: string; // "925 Sterling Silver" for silver items
  images: string[];
  videoUrl?: string; // Product Video URL or DataURL for HD ornament video display
  description: string;
  specifications: {
    material: string;
    purity?: string;
    finish: string;
    weight?: string;
  };
  variants?: ProductVariant[];
  tag: string;
  inStock: boolean;
  stockQty?: number; // Total product inventory
  isBestseller?: boolean;
  isFeatured?: boolean;
}

export const TODAY_SILVER_RATE_PER_GRAM = 95; // Default silver rate in ₹/gram

export const ALL_PRODUCTS: Product[] = [
  // ==========================================
  // SILVER COLLECTION (24 PRODUCTS)
  // ==========================================

  // --- SILVER CHAINS (6) ---
  {
    id: "at-c101",
    slug: "sterling-silver-link-chain",
    name: "Sterling Silver Link Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 18.5,
    makingCharge: 692.5,
    purity: "925 Sterling Silver",
    images: ["/Sterling Silver Link Chain.png", "/chain.category.png"],
    description: "Sleek and durable 925 sterling silver link chain designed for unisex daily wear. Features a smooth tarnish-resistant finish.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Rhodium Polish", weight: "18.5 grams" },
    tag: "Pure Silver",
    inStock: true,
    stockQty: 12,
    isBestseller: true,
  },
  {
    id: "at-c102",
    slug: "classic-silver-snake-chain",
    name: "Classic Silver Snake Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 14.0,
    makingCharge: 520,
    purity: "925 Sterling Silver",
    images: ["/chain.category.png", "/Sterling Silver Link Chain.png"],
    description: "Flexible and glossy 925 sterling silver snake chain with smooth round links.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "High Gloss Polish", weight: "14.0 grams" },
    tag: "Classic",
    inStock: true,
    stockQty: 8,
    isFeatured: true,
  },
  {
    id: "at-c103",
    slug: "heavy-silver-box-link-chain",
    name: "Heavy Silver Box Link Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 22.5,
    makingCharge: 762.5,
    purity: "925 Sterling Silver",
    images: ["/Sterling Silver Link Chain.png", "/chain.category.png"],
    description: "Robust square box-link 925 sterling silver chain engineered for extra strength.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Anti-Tarnish Polish", weight: "22.5 grams" },
    tag: "Heavy Weight",
    inStock: true,
    stockQty: 6,
  },
  {
    id: "at-c104",
    slug: "delicate-silver-rope-chain",
    name: "Delicate Silver Rope Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 11.2,
    makingCharge: 436,
    purity: "925 Sterling Silver",
    images: ["/chain.category.png", "/Sterling Silver Link Chain.png"],
    description: "Twisted 925 sterling silver rope chain that catches light effortlessly.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Diamond Cut Polish", weight: "11.2 grams" },
    tag: "Delicate",
    inStock: true,
    stockQty: 10,
  },
  {
    id: "at-c105",
    slug: "silver-figaro-pattern-chain",
    name: "Silver Figaro Pattern Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 16.0,
    makingCharge: 580,
    purity: "925 Sterling Silver",
    images: ["/Sterling Silver Link Chain.png", "/chain.category.png"],
    description: "Italian-style Figaro pattern sterling silver chain featuring alternating links.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Rhodium Finish", weight: "16.0 grams" },
    tag: "Italian Design",
    inStock: true,
    stockQty: 7,
  },
  {
    id: "at-c106",
    slug: "layered-silver-pendant-chain",
    name: "Layered Silver Pendant Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 19.8,
    makingCharge: 719,
    purity: "925 Sterling Silver",
    images: ["/chain.category.png", "/Sterling Silver Link Chain.png"],
    description: "Dual-strand 925 sterling silver chain crowned with a drop pendant.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "High Polish", weight: "19.8 grams" },
    tag: "Layered",
    inStock: true,
    stockQty: 5,
    isFeatured: true,
  },

  // --- SILVER ANKLETS (6) ---
  {
    id: "at-a201",
    slug: "silver-charm-payal-anklet-pair",
    name: "Silver Charm Payal Anklet Pair",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 14.2,
    makingCharge: 541,
    purity: "925 Sterling Silver",
    images: ["/Silver Charm Payal Anklet Pair.png", "/anklet.category.png"],
    description: "Handcrafted sterling silver payal featuring intricate bead charms.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "High-Polish Silver", weight: "14.2 grams" },
    variants: [
      { id: "size-9.5", name: '9.5 Inches (Standard)', inStock: true, stockQty: 5 },
      { id: "size-10", name: '10.0 Inches (Comfort Fit)', inStock: true, stockQty: 4 },
      { id: "size-10.5", name: '10.5 Inches', inStock: false, stockQty: 0 },
    ],
    tag: "Bestseller",
    inStock: true,
    stockQty: 9,
    isBestseller: true,
  },
  {
    id: "at-a202",
    slug: "traditional-ghungroo-silver-payal",
    name: "Traditional Ghungroo Silver Payal",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 16.8,
    makingCharge: 554,
    purity: "925 Sterling Silver",
    images: ["/Traditional Ghungroo Silver Payal.png", "/anklet.category.png"],
    description: "Melodious silver payal crafted with traditional ghungroo bells.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Oxidized Silver", weight: "16.8 grams" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 6 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 3 },
    ],
    tag: "Festive",
    inStock: true,
    stockQty: 9,
  },
  {
    id: "at-a203",
    slug: "minimalist-silver-bead-payal",
    name: "Minimalist Silver Bead Payal",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 10.5,
    makingCharge: 402.5,
    purity: "925 Sterling Silver",
    images: ["/anklet.category.png", "/Silver Charm Payal Anklet Pair.png"],
    description: "Sleek single-strand 925 sterling silver anklet accented with tiny beads.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Smooth Polish", weight: "10.5 grams" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 7 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 4 },
    ],
    tag: "Minimalist",
    inStock: true,
    stockQty: 11,
  },
  {
    id: "at-a204",
    slug: "antique-carved-oxidized-silver-payal",
    name: "Antique Carved Oxidized Silver Payal",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 21.0,
    makingCharge: 705,
    purity: "925 Sterling Silver",
    images: ["/anklet.category.png", "/Traditional Ghungroo Silver Payal.png"],
    description: "Vintage-inspired 925 oxidized silver anklet featuring heavy tribal carving.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Oxidized Antique Finish", weight: "21.0 grams" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 4 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 2 },
    ],
    tag: "Antique",
    inStock: true,
    stockQty: 6,
    isFeatured: true,
  },
  {
    id: "at-a205",
    slug: "single-layer-sleek-silver-payal",
    name: "Single Layer Sleek Silver Payal",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 12.0,
    makingCharge: 460,
    purity: "925 Sterling Silver",
    images: ["/Silver Charm Payal Anklet Pair.png", "/anklet.category.png"],
    description: "Lightweight single-layer 925 silver payal designed for daily office wear.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "High Polish", weight: "12.0 grams" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 8 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 5 },
    ],
    tag: "Everyday",
    inStock: true,
    stockQty: 13,
  },
  {
    id: "at-a206",
    slug: "royal-floral-bell-silver-payal",
    name: "Royal Floral Bell Silver Payal",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 25.5,
    makingCharge: 827.5,
    purity: "925 Sterling Silver",
    images: ["/Traditional Ghungroo Silver Payal.png", "/anklet.category.png"],
    description: "Grand bridal-style 925 sterling silver payal featuring intricate floral filigree.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Oxidized Silver", weight: "25.5 grams" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 3 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 2 },
    ],
    tag: "Royal Bridal",
    inStock: true,
    stockQty: 5,
  },

  // --- SILVER BRACELETS (6) ---
  {
    id: "at-b401",
    slug: "delicate-infinity-silver-bracelet",
    name: "Delicate Infinity Silver Bracelet",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 24.0,
    makingCharge: 920,
    purity: "925 Sterling Silver",
    images: ["/Delicate Infinity Silver Bracelet.png", "/bracelet.category.png"],
    description: "Graceful sterling silver charm bracelet featuring a delicate infinity motif.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Anti-Tarnish Polish", weight: "24.0 grams" },
    tag: "Bestseller",
    inStock: true,
    stockQty: 8,
    isBestseller: true,
  },
  {
    id: "at-b402",
    slug: "silver-bead-cuff-bracelet",
    name: "Silver Bead Cuff Bracelet",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 12.5,
    makingCharge: 462.5,
    purity: "925 Sterling Silver",
    images: ["/Silver Bead Cuff Bracelet.png", "/bracelet.category.png"],
    description: "Minimalist open-cuff 925 silver bracelet with twin polished sphere ends.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "High-Polish Silver", weight: "12.5 grams" },
    tag: "Minimalist",
    inStock: true,
    stockQty: 10,
  },
  {
    id: "at-b403",
    slug: "heavy-sterling-silver-kada",
    name: "Heavy Sterling Silver Kada",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 32.0,
    makingCharge: 860,
    purity: "925 Sterling Silver",
    images: ["/bracelet.category.png", "/Silver Bead Cuff Bracelet.png"],
    description: "Solid 925 sterling silver traditional kada designed for unisex daily wear.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Solid Silver Polish", weight: "32.0 grams" },
    tag: "Solid Silver",
    inStock: true,
    stockQty: 4,
    isFeatured: true,
  },
  {
    id: "at-b404",
    slug: "silver-heart-charm-chain-bracelet",
    name: "Silver Heart Charm Chain Bracelet",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 15.0,
    makingCharge: 525,
    purity: "925 Sterling Silver",
    images: ["/Delicate Infinity Silver Bracelet.png", "/bracelet.category.png"],
    description: "Charming 925 sterling silver link bracelet carrying a dangling heart pendant.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Rhodium Polish", weight: "15.0 grams" },
    tag: "Romantic",
    inStock: true,
    stockQty: 7,
  },
  {
    id: "at-b405",
    slug: "oxidized-silver-floral-cuff",
    name: "Oxidized Silver Floral Cuff",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 18.0,
    makingCharge: 590,
    purity: "925 Sterling Silver",
    images: ["/bracelet.category.png", "/Silver Bead Cuff Bracelet.png"],
    description: "Artisanal oxidized 925 silver open-cuff bracelet engraved with lotus motifs.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Oxidized Silver", weight: "18.0 grams" },
    tag: "Artisanal",
    inStock: true,
    stockQty: 6,
  },
  {
    id: "at-b406",
    slug: "interlocking-silver-circle-bracelet",
    name: "Interlocking Silver Circle Bracelet",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "silver",
    pricingType: "weight_based",
    weightGrams: 13.8,
    makingCharge: 489,
    purity: "925 Sterling Silver",
    images: ["/Delicate Infinity Silver Bracelet.png", "/bracelet.category.png"],
    description: "Sleek 925 sterling silver bracelet featuring dual interlocking circles.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Mirror Polish", weight: "13.8 grams" },
    tag: "Geometric",
    inStock: true,
    stockQty: 9,
  },

  // --- SILVER RINGS (6) ---
  {
    id: "at-r301",
    slug: "minimal-sterling-silver-solitaire-ring",
    name: "Minimal Sterling Silver Solitaire Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "silver",
    pricingType: "fixed",
    fixedPrice: 799,
    purity: "925 Sterling Silver",
    images: ["/Minimal Sterling Silver Solitaire Ring.png", "/ring.category.png"],
    description: "Timeless 925 sterling silver solitaire ring crowned with a stone setting.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "High-Shine Silver" },
    variants: [
      { id: "ring-sz-12", name: "Size 12 (16.5 mm)", inStock: true, stockQty: 4 },
      { id: "ring-sz-14", name: "Size 14 (17.3 mm)", inStock: true, stockQty: 5 },
      { id: "ring-sz-16", name: "Size 16 (18.1 mm)", inStock: true, stockQty: 3 },
      { id: "ring-sz-18", name: "Size 18 (18.9 mm)", inStock: false, stockQty: 0 },
    ],
    tag: "Signature",
    inStock: true,
    stockQty: 12,
    isBestseller: true,
  },
  {
    id: "at-r302",
    slug: "traditional-oxidized-silver-adjustable-ring",
    name: "Traditional Oxidized Silver Adjustable Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "silver",
    pricingType: "fixed",
    fixedPrice: 650,
    purity: "925 Sterling Silver",
    images: ["/ring.category.png", "/Minimal Sterling Silver Solitaire Ring.png"],
    description: "Intricately carved oxidized 925 silver ring with flexible open band.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Oxidized Finish" },
    variants: [
      { id: "ring-free", name: "Free Size (Adjustable)", inStock: true, stockQty: 15 },
    ],
    tag: "Ethnic",
    inStock: true,
    stockQty: 15,
    isFeatured: true,
  },
  {
    id: "at-r303",
    slug: "sterling-silver-dual-band-ring",
    name: "Sterling Silver Dual Band Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "silver",
    pricingType: "fixed",
    fixedPrice: 890,
    purity: "925 Sterling Silver",
    images: ["/Minimal Sterling Silver Solitaire Ring.png", "/ring.category.png"],
    description: "Modern dual-layer parallel band ring crafted in pure 925 sterling silver.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Rhodium Polish" },
    variants: [
      { id: "sz-12", name: "Size 12", inStock: true, stockQty: 3 },
      { id: "sz-14", name: "Size 14", inStock: true, stockQty: 4 },
      { id: "sz-16", name: "Size 16", inStock: true, stockQty: 2 },
    ],
    tag: "Modern",
    inStock: true,
    stockQty: 9,
  },
  {
    id: "at-r304",
    slug: "silver-crown-zircon-ring",
    name: "Silver Crown Zircon Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "silver",
    pricingType: "fixed",
    fixedPrice: 999,
    purity: "925 Sterling Silver",
    images: ["/ring.category.png", "/Minimal Sterling Silver Solitaire Ring.png"],
    description: "Regal crown motif ring studded with AAA grade zircon stones.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Anti-Tarnish Polish" },
    variants: [
      { id: "sz-12", name: "Size 12", inStock: true, stockQty: 2 },
      { id: "sz-14", name: "Size 14", inStock: true, stockQty: 4 },
      { id: "sz-16", name: "Size 16", inStock: true, stockQty: 1 },
    ],
    tag: "Crown Collection",
    inStock: true,
    stockQty: 7,
  },
  {
    id: "at-r305",
    slug: "vintage-engraved-silver-signet-ring",
    name: "Vintage Engraved Silver Signet Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "silver",
    pricingType: "fixed",
    fixedPrice: 1150,
    purity: "925 Sterling Silver",
    images: ["/Minimal Sterling Silver Solitaire Ring.png", "/ring.category.png"],
    description: "Bold vintage signet ring in heavy 925 sterling silver with starburst engraving.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "High Polish" },
    variants: [
      { id: "sz-14", name: "Size 14", inStock: true, stockQty: 3 },
      { id: "sz-16", name: "Size 16", inStock: true, stockQty: 2 },
      { id: "sz-18", name: "Size 18", inStock: true, stockQty: 1 },
    ],
    tag: "Vintage Signet",
    inStock: true,
    stockQty: 6,
  },
  {
    id: "at-r306",
    slug: "curved-silver-wave-stackable-ring",
    name: "Curved Silver Wave Stackable Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "silver",
    pricingType: "fixed",
    fixedPrice: 599,
    purity: "925 Sterling Silver",
    images: ["/ring.category.png", "/Minimal Sterling Silver Solitaire Ring.png"],
    description: "Delicate organic wave ring crafted in 925 sterling silver, perfect for stacking.",
    specifications: { material: "Sterling Silver", purity: "925 Sterling Silver", finish: "Smooth Polish" },
    variants: [
      { id: "sz-12", name: "Size 12", inStock: true, stockQty: 5 },
      { id: "sz-14", name: "Size 14", inStock: true, stockQty: 4 },
      { id: "sz-16", name: "Size 16", inStock: true, stockQty: 3 },
    ],
    tag: "Stackable",
    inStock: true,
    stockQty: 12,
  },

  // ==========================================
  // ARTIFICIAL COLLECTION (24 PRODUCTS)
  // ==========================================

  // --- ARTIFICIAL CHAINS (6) ---
  {
    id: "at-art-c1",
    slug: "rose-gold-plated-minimalist-chain",
    name: "Rose Gold Plated Minimalist Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 499,
    images: ["/chain.category.png", "/Sterling Silver Link Chain.png"],
    description: "Chic rose gold plated brass chain with anti-tarnish coating.",
    specifications: { material: "Brass Alloy", finish: "Rose Gold Plated" },
    tag: "Fashion Pick",
    inStock: true,
    stockQty: 15,
    isBestseller: true,
  },
  {
    id: "at-art-c2",
    slug: "golden-cz-crystal-layered-necklace",
    name: "Golden CZ Crystal Layered Necklace",
    category: "chain",
    categoryLabel: "Chain",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 799,
    images: ["/Sterling Silver Link Chain.png", "/chain.category.png"],
    description: "Dual-layer golden chain featuring sparkling cubic zirconia crystal pendants.",
    specifications: { material: "Alloy & CZ Stones", finish: "18K Gold Tone" },
    tag: "Glamour",
    inStock: true,
    stockQty: 10,
  },
  {
    id: "at-art-c3",
    slug: "traditional-kundan-choker-chain",
    name: "Traditional Kundan Choker Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 1299,
    images: ["/chain.category.png", "/Sterling Silver Link Chain.png"],
    description: "Festive Kundan choker chain embellished with faux pearls and green stone drops.",
    specifications: { material: "Brass Kundan & Faux Pearls", finish: "Antique Gold Plating" },
    tag: "Festive Kundan",
    inStock: true,
    stockQty: 6,
    isFeatured: true,
  },
  {
    id: "at-art-c4",
    slug: "anti-tarnish-dual-coin-chain",
    name: "Anti-Tarnish Dual Coin Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 599,
    images: ["/Sterling Silver Link Chain.png", "/chain.category.png"],
    description: "Waterproof anti-tarnish stainless steel chain decorated with Roman coin medallions.",
    specifications: { material: "Stainless Steel", finish: "PVD Gold Plated" },
    tag: "Waterproof",
    inStock: true,
    stockQty: 14,
  },
  {
    id: "at-art-c5",
    slug: "emerald-stone-pendant-chain",
    name: "Emerald Stone Pendant Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 699,
    images: ["/chain.category.png", "/Sterling Silver Link Chain.png"],
    description: "Elegant golden chain featuring a faux emerald teardrop crystal setting.",
    specifications: { material: "Alloy & Faux Emerald", finish: "Gold Polish" },
    tag: "Party Wear",
    inStock: true,
    stockQty: 8,
  },
  {
    id: "at-art-c6",
    slug: "matte-gold-temple-work-chain",
    name: "Matte Gold Temple Work Chain",
    category: "chain",
    categoryLabel: "Chain",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 899,
    images: ["/Sterling Silver Link Chain.png", "/chain.category.png"],
    description: "South Indian traditional temple design chain with goddess motifs.",
    specifications: { material: "Copper Alloy", finish: "Matte Gold Finish" },
    tag: "Temple Design",
    inStock: true,
    stockQty: 7,
  },

  // --- ARTIFICIAL ANKLETS (6) ---
  {
    id: "at-art-a1",
    slug: "golden-pearl-charm-payal-pair",
    name: "Golden Pearl Charm Payal Pair",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 449,
    images: ["/anklet.category.png", "/Silver Charm Payal Anklet Pair.png"],
    description: "Dainty golden payal pair adorned with miniature pearl droplets.",
    specifications: { material: "Alloy & Faux Pearls", finish: "Gold Plated" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 6 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 4 },
    ],
    tag: "Pearl Collection",
    inStock: true,
    stockQty: 10,
  },
  {
    id: "at-art-a2",
    slug: "minimalist-crystal-strand-anklet",
    name: "Minimalist Crystal Strand Anklet",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 399,
    images: ["/Silver Charm Payal Anklet Pair.png", "/anklet.category.png"],
    description: "Subtle single-line crystal chain anklet designed for beach outfits.",
    specifications: { material: "Brass & Crystals", finish: "Silver Tone Plated" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 8 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 5 },
    ],
    tag: "Summer Essential",
    inStock: true,
    stockQty: 13,
  },
  {
    id: "at-art-a3",
    slug: "boho-coin-shell-charm-anklet",
    name: "Boho Coin & Shell Charm Anklet",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 499,
    images: ["/anklet.category.png", "/Traditional Ghungroo Silver Payal.png"],
    description: "Bohemian-style multi-layer anklet carrying metal coins and sea shell charms.",
    specifications: { material: "Mixed Metal & Shells", finish: "Antique Finish" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 9 },
    ],
    tag: "Boho Chic",
    inStock: true,
    stockQty: 9,
  },
  {
    id: "at-art-a4",
    slug: "rose-gold-infinity-anklet",
    name: "Rose Gold Infinity Anklet",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 549,
    images: ["/Silver Charm Payal Anklet Pair.png", "/anklet.category.png"],
    description: "Contemporary rose gold anklet centered with an infinity charm.",
    specifications: { material: "Stainless Steel", finish: "Rose Gold PVD" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 5 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 3 },
    ],
    tag: "Modern",
    inStock: true,
    stockQty: 8,
    isFeatured: true,
  },
  {
    id: "at-art-a5",
    slug: "traditional-bridal-kundan-payal",
    name: "Traditional Bridal Kundan Payal",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 999,
    images: ["/Traditional Ghungroo Silver Payal.png", "/anklet.category.png"],
    description: "Heavy wedding Kundan payal pair embellished with ruby red stones.",
    specifications: { material: "Brass Kundan & Stones", finish: "Gold Plated" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 4 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 2 },
    ],
    tag: "Bridal Special",
    inStock: true,
    stockQty: 6,
  },
  {
    id: "at-art-a6",
    slug: "dual-layered-beaded-golden-anklet",
    name: "Dual Layered Beaded Golden Anklet",
    category: "anklet",
    categoryLabel: "Anklet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 429,
    images: ["/anklet.category.png", "/Silver Charm Payal Anklet Pair.png"],
    description: "Lightweight double-layered golden payal string studded with black and gold beads.",
    specifications: { material: "Alloy & Beads", finish: "Gold Finish" },
    variants: [
      { id: "sz-9.5", name: '9.5 Inches', inStock: true, stockQty: 7 },
      { id: "sz-10", name: '10.0 Inches', inStock: true, stockQty: 4 },
    ],
    tag: "Everyday",
    inStock: true,
    stockQty: 11,
  },

  // --- ARTIFICIAL BRACELETS (6) ---
  {
    id: "at-art-b1",
    slug: "american-diamond-solitaire-bangle-bracelet",
    name: "American Diamond Solitaire Bangle Bracelet",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 899,
    images: ["/bracelet.category.png", "/Delicate Infinity Silver Bracelet.png"],
    description: "Sparkling American Diamond openable oval bangle bracelet.",
    specifications: { material: "Brass & AAA CZ Stones", finish: "Rhodium Gold Finish" },
    tag: "Glamour",
    inStock: true,
    stockQty: 9,
  },
  {
    id: "at-art-b2",
    slug: "rose-gold-adjustable-oval-bracelet",
    name: "Rose Gold Adjustable Oval Bracelet",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 649,
    images: ["/Delicate Infinity Silver Bracelet.png", "/bracelet.category.png"],
    description: "Sleek rose-gold plated flexible cuff decorated with crystal pavé.",
    specifications: { material: "Stainless Steel", finish: "Rose Gold Finish" },
    tag: "Chic",
    inStock: true,
    stockQty: 12,
  },
  {
    id: "at-art-b3",
    slug: "traditional-temple-work-open-cuff",
    name: "Traditional Temple Work Open Cuff",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 799,
    images: ["/Silver Bead Cuff Bracelet.png", "/bracelet.category.png"],
    description: "South Indian traditional matte gold kada with elephant motifs.",
    specifications: { material: "Copper Alloy", finish: "Antique Matte Gold" },
    tag: "Temple Artwork",
    inStock: true,
    stockQty: 5,
    isFeatured: true,
  },
  {
    id: "at-art-b4",
    slug: "pearl-strand-charm-bracelet",
    name: "Pearl Strand Charm Bracelet",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 499,
    images: ["/Delicate Infinity Silver Bracelet.png", "/bracelet.category.png"],
    description: "Elasticized freshwater-look pearl bracelet decorated with a golden coin charm.",
    specifications: { material: "Faux Pearls & Alloy", finish: "Gold Tone" },
    tag: "Classic Pearl",
    inStock: true,
    stockQty: 11,
  },
  {
    id: "at-art-b5",
    slug: "matte-gold-floral-bangle-pair",
    name: "Matte Gold Floral Bangle Pair",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 699,
    images: ["/bracelet.category.png", "/Silver Bead Cuff Bracelet.png"],
    description: "Set of 2 matte-finish floral engraved golden bangles.",
    specifications: { material: "Brass Alloy", finish: "Matte Gold" },
    tag: "Ethnic Pair",
    inStock: true,
    stockQty: 8,
  },
  {
    id: "at-art-b6",
    slug: "crystal-evil-eye-charm-bracelet",
    name: "Crystal Evil Eye Charm Bracelet",
    category: "bracelet",
    categoryLabel: "Bracelet",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 599,
    images: ["/Delicate Infinity Silver Bracelet.png", "/bracelet.category.png"],
    description: "Protection symbol blue crystal evil eye charm attached to an adjustable chain.",
    specifications: { material: "Enamel & Alloy", finish: "18K Gold Plated" },
    tag: "Protection Charm",
    inStock: true,
    stockQty: 14,
  },

  // --- ARTIFICIAL RINGS (6) ---
  {
    id: "at-art-r1",
    slug: "american-diamond-statement-cocktail-ring",
    name: "American Diamond Statement Cocktail Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 699,
    images: ["/ring.category.png", "/Minimal Sterling Silver Solitaire Ring.png"],
    description: "Glamorous floral cocktail ring encrusted with brilliant American Diamonds.",
    specifications: { material: "Brass & AAA CZ Crystals", finish: "Rhodium Finish" },
    variants: [{ id: "ring-free", name: "Free Size (Adjustable)", inStock: true, stockQty: 12 }],
    tag: "Bestseller",
    inStock: true,
    stockQty: 12,
    isBestseller: true,
  },
  {
    id: "at-art-r2",
    slug: "rose-gold-floral-crystal-ring",
    name: "Rose Gold Floral Crystal Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 499,
    images: ["/Minimal Sterling Silver Solitaire Ring.png", "/ring.category.png"],
    description: "Feminine rose-gold ring featuring a blooming crystal flower centerpiece.",
    specifications: { material: "Alloy & Crystals", finish: "Rose Gold Plated" },
    variants: [
      { id: "sz-12", name: "Size 12", inStock: true, stockQty: 4 },
      { id: "sz-14", name: "Size 14", inStock: true, stockQty: 3 },
    ],
    tag: "Feminine",
    inStock: true,
    stockQty: 7,
  },
  {
    id: "at-art-r3",
    slug: "traditional-kundan-adjustable-ring",
    name: "Traditional Kundan Adjustable Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 599,
    images: ["/ring.category.png", "/Minimal Sterling Silver Solitaire Ring.png"],
    description: "Big round Kundan ring framed with pearl meenakari detailing.",
    specifications: { material: "Brass Kundan", finish: "Antique Gold" },
    variants: [{ id: "ring-free", name: "Free Size (Adjustable)", inStock: true, stockQty: 10 }],
    tag: "Festive Kundan",
    inStock: true,
    stockQty: 10,
    isFeatured: true,
  },
  {
    id: "at-art-r4",
    slug: "emerald-cut-zircon-solitaire-ring",
    name: "Emerald Cut Zircon Solitaire Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 549,
    images: ["/Minimal Sterling Silver Solitaire Ring.png", "/ring.category.png"],
    description: "Sophisticated rectangular emerald-cut zircon solitaire ring.",
    specifications: { material: "Alloy & Zircon", finish: "Gold Finish" },
    variants: [
      { id: "sz-12", name: "Size 12", inStock: true, stockQty: 5 },
      { id: "sz-14", name: "Size 14", inStock: true, stockQty: 3 },
    ],
    tag: "Solitaire",
    inStock: true,
    stockQty: 8,
  },
  {
    id: "at-art-r5",
    slug: "antique-gold-floral-statement-ring",
    name: "Antique Gold Floral Statement Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 649,
    images: ["/ring.category.png", "/Minimal Sterling Silver Solitaire Ring.png"],
    description: "Royal antique gold ring with lotus motif and ruby red crystal stone.",
    specifications: { material: "Copper Alloy", finish: "Antique Gold" },
    variants: [{ id: "ring-free", name: "Free Size (Adjustable)", inStock: true, stockQty: 6 }],
    tag: "Royal",
    inStock: true,
    stockQty: 6,
  },
  {
    id: "at-art-r6",
    slug: "minimal-stackable-rose-gold-band-ring",
    name: "Minimal Stackable Rose Gold Band Ring",
    category: "ring",
    categoryLabel: "Ring",
    collection: "artificial",
    pricingType: "fixed",
    fixedPrice: 349,
    images: ["/Minimal Sterling Silver Solitaire Ring.png", "/ring.category.png"],
    description: "Ultra-thin rose gold band ring designed for effortless daily stacking.",
    specifications: { material: "Stainless Steel", finish: "Rose Gold PVD" },
    variants: [
      { id: "sz-12", name: "Size 12", inStock: true, stockQty: 6 },
      { id: "sz-14", name: "Size 14", inStock: true, stockQty: 4 },
      { id: "sz-16", name: "Size 16", inStock: true, stockQty: 5 },
    ],
    tag: "Daily Stack",
    inStock: true,
    stockQty: 15,
  },
];

let cachedProductsList: Product[] | null = null;

export function getEffectiveProducts(): Product[] {
  if (cachedProductsList !== null) return cachedProductsList;
  if (typeof window === "undefined") return ALL_PRODUCTS;

  try {
    const saved = localStorage.getItem("at_custom_products");
    if (saved) {
      const parsed = JSON.parse(saved);
      if (Array.isArray(parsed) && parsed.length > 0) {
        cachedProductsList = parsed;
        return parsed;
      }
    }
  } catch (e) {
    console.error("Error reading at_custom_products:", e);
  }

  return ALL_PRODUCTS;
}

export function setEffectiveProductsCache(products: Product[]) {
  if (Array.isArray(products) && products.length > 0) {
    cachedProductsList = products;
    if (typeof window !== "undefined") {
      try {
        localStorage.setItem("at_custom_products", JSON.stringify(products));
      } catch (e) {}
    }
  }
}

export function clearProductCache() {
  cachedProductsList = null;
}

// Reduce inventory upon placing order
export function reduceProductInventory(productId: string, quantity: number = 1, variantName?: string) {
  if (typeof window === "undefined") return;

  const currentList = getEffectiveProducts();
  const updated = currentList.map((p) => {
    if (p.id === productId) {
      let newTotalQty = Math.max(0, (p.stockQty ?? 10) - quantity);
      let updatedVariants = p.variants;

      if (p.variants && p.variants.length > 0) {
        updatedVariants = p.variants.map((v) => {
          if (!variantName || v.name === variantName) {
            const newVarQty = Math.max(0, (v.stockQty ?? 5) - quantity);
            return {
              ...v,
              stockQty: newVarQty,
              inStock: newVarQty > 0,
            };
          }
          return v;
        });

        const anyVarInStock = updatedVariants.some((v) => v.inStock);
        return {
          ...p,
          stockQty: newTotalQty,
          inStock: anyVarInStock,
          variants: updatedVariants,
        };
      }

      return {
        ...p,
        stockQty: newTotalQty,
        inStock: newTotalQty > 0,
      };
    }
    return p;
  });

  cachedProductsList = updated;
  localStorage.setItem("at_custom_products", JSON.stringify(updated));
}
