import { BoundedAction } from "../../lib/recovery/types";

export interface LabeledFunnelEvent {
  id: number;
  name: string;
  category:
    | "price_sensitive"
    | "payment_friction"
    | "authorized_uncaptured"
    | "first_time_visitor"
    | "repeat_customer"
    | "too_early"
    | "conflicting_signals";
  input: {
    eventType: string;
    cartTotal: number;
    timeSinceEventHours: number;
    paymentAttemptStatus: string;
    customerPurchaseHistoryCount: number;
    productCategory: string;
    rawContext?: any;
  };
  expectedAction: BoundedAction;
  expectedMaxDiscountPercent: number; // 0, 5, 10
  shouldAct: boolean; // true if expectedAction !== "no_action"
  labelReasoning: string;
}

// -------------------------------------------------------------
// DEV DATASET (30 EVENTS) — Used for prompt tuning & validation
// -------------------------------------------------------------
export const DEV_DATASET_30: LabeledFunnelEvent[] = [
  // Price-Sensitive Abandonments (1-6)
  {
    id: 1,
    name: "Dev-PS1: High Value Anklet Abandonment (3.5h)",
    category: "price_sensitive",
    input: { eventType: "cart_abandoned", cartTotal: 5800, timeSinceEventHours: 3.5, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 2, productCategory: "anklet" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "Repeat customer with high cart total idle 3.5h. High price sensitivity warranting discount nudge.",
  },
  {
    id: 2,
    name: "Dev-PS2: Premium Chain Cart Abandoned (2.0h)",
    category: "price_sensitive",
    input: { eventType: "cart_abandoned", cartTotal: 7200, timeSinceEventHours: 2.0, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 1, productCategory: "chain" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "High-value chain cart abandoned over 2 hours ago by repeat buyer.",
  },
  {
    id: 3,
    name: "Dev-PS3: Moderate Value Payal Idle (4.0h)",
    category: "price_sensitive",
    input: { eventType: "cart_abandoned", cartTotal: 3400, timeSinceEventHours: 4.0, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 3, productCategory: "anklet" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "Multiple repeat buyer idling 4h on moderate payal total.",
  },
  {
    id: 4,
    name: "Dev-PS4: High Value Ring Abandonment (2.5h)",
    category: "price_sensitive",
    input: { eventType: "cart_abandoned", cartTotal: 4900, timeSinceEventHours: 2.5, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 1, productCategory: "ring" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "High value ring cart idle 2.5h by customer with prior purchase history.",
  },
  {
    id: 5,
    name: "Dev-PS5: Silver Bracelet Bundle Idle (5.0h)",
    category: "price_sensitive",
    input: { eventType: "cart_abandoned", cartTotal: 8500, timeSinceEventHours: 5.0, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 4, productCategory: "bracelet" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "Loyal repeat buyer with 8.5k cart total idle 5 hours.",
  },
  {
    id: 6,
    name: "Dev-PS6: Silver Chain Combo Abandoned (3.0h)",
    category: "price_sensitive",
    input: { eventType: "cart_abandoned", cartTotal: 6100, timeSinceEventHours: 3.0, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 2, productCategory: "chain" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "High total silver chain combo abandoned 3h ago.",
  },

  // Payment Friction Failures (7-12)
  {
    id: 7,
    name: "Dev-PF1: Bank Gateway Timeout (1.2h)",
    category: "payment_friction",
    input: { eventType: "payment_failed", cartTotal: 3200, timeSinceEventHours: 1.2, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 1, productCategory: "anklet", rawContext: { reason: "Bank OTP timeout" } },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Payment failed due to OTP timeout. Technical friction; requires retry payment link with 0% discount.",
  },
  {
    id: 8,
    name: "Dev-PF2: Card Authorization Failed (1.5h)",
    category: "payment_friction",
    input: { eventType: "payment_failed", cartTotal: 4500, timeSinceEventHours: 1.5, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 0, productCategory: "chain", rawContext: { reason: "Card 3DS failure" } },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "3DS authentication failure. Technical issue, zero price resistance.",
  },
  {
    id: 9,
    name: "Dev-PF3: UPI Server Down (2.0h)",
    category: "payment_friction",
    input: { eventType: "payment_failed", cartTotal: 2800, timeSinceEventHours: 2.0, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 2, productCategory: "ring", rawContext: { reason: "NPCI UPI timeout" } },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "NPCI UPI server timeout. Pure gateway friction, send retry link.",
  },
  {
    id: 10,
    name: "Dev-PF4: Insufficient Funds Failure (1.8h)",
    category: "payment_friction",
    input: { eventType: "payment_failed", cartTotal: 5200, timeSinceEventHours: 1.8, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 1, productCategory: "bracelet", rawContext: { reason: "Bank limit exceeded" } },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Payment failed at bank. Retry option without discount.",
  },
  {
    id: 11,
    name: "Dev-PF5: Network Drop at Checkout (1.1h)",
    category: "payment_friction",
    input: { eventType: "payment_failed", cartTotal: 1900, timeSinceEventHours: 1.1, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 0, productCategory: "anklet", rawContext: { reason: "Connection reset" } },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Network connection dropped during checkout modal. Retry required.",
  },
  {
    id: 12,
    name: "Dev-PF6: Bank System Maintenance (2.2h)",
    category: "payment_friction",
    input: { eventType: "payment_failed", cartTotal: 3900, timeSinceEventHours: 2.2, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 3, productCategory: "chain", rawContext: { reason: "Bank maintenance" } },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Bank downtime during transaction. Retry payment link.",
  },

  // Authorized Not Captured (13-16)
  {
    id: 13,
    name: "Dev-AUC1: Authorized Payment Pending Capture (1.5h)",
    category: "authorized_uncaptured",
    input: { eventType: "authorized_not_captured", cartTotal: 6500, timeSinceEventHours: 1.5, paymentAttemptStatus: "authorized_not_captured", customerPurchaseHistoryCount: 2, productCategory: "anklet" },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Payment is already authorized by bank. Hard policy rule forbids discount! Only retry payment link.",
  },
  {
    id: 14,
    name: "Dev-AUC2: Authorized High Value Chain (3.0h)",
    category: "authorized_uncaptured",
    input: { eventType: "authorized_not_captured", cartTotal: 9800, timeSinceEventHours: 3.0, paymentAttemptStatus: "authorized_not_captured", customerPurchaseHistoryCount: 5, productCategory: "chain" },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "High value order authorized but uncaptured. Zero discount allowed by policy gate.",
  },
  {
    id: 15,
    name: "Dev-AUC3: Authorized Payal Pair (2.0h)",
    category: "authorized_uncaptured",
    input: { eventType: "authorized_not_captured", cartTotal: 4200, timeSinceEventHours: 2.0, paymentAttemptStatus: "authorized_not_captured", customerPurchaseHistoryCount: 1, productCategory: "anklet" },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Payment authorized at bank. Zero discount, send payment verification link.",
  },
  {
    id: 16,
    name: "Dev-AUC4: Authorized Ring Order (1.8h)",
    category: "authorized_uncaptured",
    input: { eventType: "authorized_not_captured", cartTotal: 3100, timeSinceEventHours: 1.8, paymentAttemptStatus: "authorized_not_captured", customerPurchaseHistoryCount: 0, productCategory: "ring" },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Authorized payment for first-time buyer. Gate enforces 0% discount and retry payment link.",
  },

  // First Time Visitors (17-21)
  {
    id: 17,
    name: "Dev-FTV1: Low Value Payal Cart (2.0h)",
    category: "first_time_visitor",
    input: { eventType: "cart_abandoned", cartTotal: 1200, timeSinceEventHours: 2.0, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 0, productCategory: "anklet" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "First-time visitor with low value cart. Reminder preferred over discount per business rule.",
  },
  {
    id: 18,
    name: "Dev-FTV2: Moderate Value Chain Cart (1.5h)",
    category: "first_time_visitor",
    input: { eventType: "cart_abandoned", cartTotal: 2100, timeSinceEventHours: 1.5, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 0, productCategory: "chain" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "First-time visitor. Trust building reminder without discount.",
  },
  {
    id: 19,
    name: "Dev-FTV3: Single Ring Abandoned (2.5h)",
    category: "first_time_visitor",
    input: { eventType: "cart_abandoned", cartTotal: 1500, timeSinceEventHours: 2.5, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 0, productCategory: "ring" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "First-time visitor single ring abandonment. Reminder action.",
  },
  {
    id: 20,
    name: "Dev-FTV4: Dainty Payal Idle (3.0h)",
    category: "first_time_visitor",
    input: { eventType: "cart_abandoned", cartTotal: 1850, timeSinceEventHours: 3.0, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 0, productCategory: "anklet" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "First-time visitor payal cart. Trust reminder nudge.",
  },
  {
    id: 21,
    name: "Dev-FTV5: Silver Charm Bracelet (2.2h)",
    category: "first_time_visitor",
    input: { eventType: "cart_abandoned", cartTotal: 2400, timeSinceEventHours: 2.2, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 0, productCategory: "bracelet" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "First-time visitor bracelet cart. Send friendly checkout reminder.",
  },

  // Repeat Customers (22-25)
  {
    id: 22,
    name: "Dev-RC1: Repeat Buyer Low Value Cart (2.0h)",
    category: "repeat_customer",
    input: { eventType: "cart_abandoned", cartTotal: 2200, timeSinceEventHours: 2.0, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 3, productCategory: "anklet" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Repeat customer with modest cart value. Standard reminder first.",
  },
  {
    id: 23,
    name: "Dev-RC2: Repeat Buyer Moderate Cart (1.8h)",
    category: "repeat_customer",
    input: { eventType: "cart_abandoned", cartTotal: 2900, timeSinceEventHours: 1.8, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 1, productCategory: "ring" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Repeat buyer 1.8h idle. Gentle reminder action.",
  },
  {
    id: 24,
    name: "Dev-RC3: Repeat Buyer Chain Abandoned (4.5h)",
    category: "repeat_customer",
    input: { eventType: "cart_abandoned", cartTotal: 5400, timeSinceEventHours: 4.5, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 2, productCategory: "chain" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "Repeat buyer idle 4.5h on high value chain. Discount appropriate.",
  },
  {
    id: 25,
    name: "Dev-RC4: Repeat Buyer Payal Idle (2.8h)",
    category: "repeat_customer",
    input: { eventType: "cart_abandoned", cartTotal: 3800, timeSinceEventHours: 2.8, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 4, productCategory: "anklet" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "Frequent buyer (4 past orders) with ₹3.8k payal cart idle nearly 3 hours.",
  },

  // Too Early Cases (< 1.0h) (26-28)
  {
    id: 26,
    name: "Dev-TE1: Cart Idle Just 20 Mins (0.33h)",
    category: "too_early",
    input: { eventType: "cart_abandoned", cartTotal: 6500, timeSinceEventHours: 0.33, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 2, productCategory: "anklet" },
    expectedAction: "no_action",
    expectedMaxDiscountPercent: 0,
    shouldAct: false,
    labelReasoning: "Elapsed time 0.33h < 1.0h threshold. Must return no_action per hard rule.",
  },
  {
    id: 27,
    name: "Dev-TE2: Payment Failure Just 15 Mins Ago (0.25h)",
    category: "too_early",
    input: { eventType: "payment_failed", cartTotal: 4200, timeSinceEventHours: 0.25, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 1, productCategory: "chain" },
    expectedAction: "no_action",
    expectedMaxDiscountPercent: 0,
    shouldAct: false,
    labelReasoning: "Elapsed time 0.25h < 1.0h. Too early to intervene.",
  },
  {
    id: 28,
    name: "Dev-TE3: High Value Cart Idle 45 Mins (0.75h)",
    category: "too_early",
    input: { eventType: "cart_abandoned", cartTotal: 9000, timeSinceEventHours: 0.75, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 3, productCategory: "bracelet" },
    expectedAction: "no_action",
    expectedMaxDiscountPercent: 0,
    shouldAct: false,
    labelReasoning: "High cart value but elapsed time 0.75h < 1.0h limit. No action permitted yet.",
  },

  // Conflicting Signal Cases (29-30)
  {
    id: 29,
    name: "Dev-CS1: High Cart Value + First Time + Too Recent (0.4h)",
    category: "conflicting_signals",
    input: { eventType: "cart_abandoned", cartTotal: 12500, timeSinceEventHours: 0.4, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 0, productCategory: "chain" },
    expectedAction: "no_action",
    expectedMaxDiscountPercent: 0,
    shouldAct: false,
    labelReasoning: "High cart total pushes for action, but elapsed time < 1h takes absolute priority -> no_action.",
  },
  {
    id: 30,
    name: "Dev-CS2: Authorized Payment + High Value + Repeat Buyer (2.5h)",
    category: "conflicting_signals",
    input: { eventType: "authorized_not_captured", cartTotal: 11000, timeSinceEventHours: 2.5, paymentAttemptStatus: "authorized_not_captured", customerPurchaseHistoryCount: 5, productCategory: "anklet" },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "High value + repeat buyer tempts a discount, but authorized status strictly forces retry_payment_link with 0% discount.",
  },
];

// -------------------------------------------------------------
// HELD-OUT DATASET (15 EVENTS) — Strictly reserved for final scoring
// -------------------------------------------------------------
export const HELD_OUT_DATASET_15: LabeledFunnelEvent[] = [
  {
    id: 31,
    name: "HeldOut-PS1: Heavy Payal Cart Idle (3.2h)",
    category: "price_sensitive",
    input: { eventType: "cart_abandoned", cartTotal: 6800, timeSinceEventHours: 3.2, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 2, productCategory: "anklet" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "Repeat customer (2 orders) with ₹6.8k payal cart idle 3.2h. Price sensitivity nudging discount.",
  },
  {
    id: 32,
    name: "HeldOut-PS2: Designer Silver Chain Abandoned (2.8h)",
    category: "price_sensitive",
    input: { eventType: "cart_abandoned", cartTotal: 5500, timeSinceEventHours: 2.8, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 1, productCategory: "chain" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "Repeat buyer with ₹5.5k chain cart abandoned 2.8h ago.",
  },
  {
    id: 33,
    name: "HeldOut-PS3: Solitaire Ring Set Idle (4.2h)",
    category: "price_sensitive",
    input: { eventType: "cart_abandoned", cartTotal: 4600, timeSinceEventHours: 4.2, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 3, productCategory: "ring" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "3-time repeat buyer idle 4.2 hours on ₹4.6k ring set.",
  },
  {
    id: 34,
    name: "HeldOut-PF1: Gateway 3DS Challenge Timeout (1.4h)",
    category: "payment_friction",
    input: { eventType: "payment_failed", cartTotal: 3700, timeSinceEventHours: 1.4, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 1, productCategory: "anklet", rawContext: { reason: "3DS timeout" } },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Gateway 3DS timeout. Technical friction requiring payment retry.",
  },
  {
    id: 35,
    name: "HeldOut-PF2: Bank Card Security Decline (1.6h)",
    category: "payment_friction",
    input: { eventType: "payment_failed", cartTotal: 5100, timeSinceEventHours: 1.6, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 0, productCategory: "chain", rawContext: { reason: "Security flag" } },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Bank security flag during card auth. Technical retry, zero discount.",
  },
  {
    id: 36,
    name: "HeldOut-PF3: UPI App Connection Failure (2.1h)",
    category: "payment_friction",
    input: { eventType: "payment_failed", cartTotal: 2900, timeSinceEventHours: 2.1, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 2, productCategory: "bracelet", rawContext: { reason: "UPI app fail" } },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "UPI app connection failed. Gateway issue requiring retry link.",
  },
  {
    id: 37,
    name: "HeldOut-AUC1: Authorized Payal Order Pending Capture (2.4h)",
    category: "authorized_uncaptured",
    input: { eventType: "authorized_not_captured", cartTotal: 7400, timeSinceEventHours: 2.4, paymentAttemptStatus: "authorized_not_captured", customerPurchaseHistoryCount: 3, productCategory: "anklet" },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Payment authorized at bank. Policy gate forbids discount! Only retry payment link.",
  },
  {
    id: 38,
    name: "HeldOut-AUC2: Authorized Chain Order Pending Capture (1.9h)",
    category: "authorized_uncaptured",
    input: { eventType: "authorized_not_captured", cartTotal: 5200, timeSinceEventHours: 1.9, paymentAttemptStatus: "authorized_not_captured", customerPurchaseHistoryCount: 0, productCategory: "chain" },
    expectedAction: "retry_payment",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Authorized payment for first-time buyer. Gate forces retry payment link with 0% discount.",
  },
  {
    id: 39,
    name: "HeldOut-FTV1: Low Value Ring Cart (1.8h)",
    category: "first_time_visitor",
    input: { eventType: "cart_abandoned", cartTotal: 1350, timeSinceEventHours: 1.8, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 0, productCategory: "ring" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "First time visitor low value cart. Reminder preferred over discount.",
  },
  {
    id: 40,
    name: "HeldOut-FTV2: Modest Payal Cart (2.5h)",
    category: "first_time_visitor",
    input: { eventType: "cart_abandoned", cartTotal: 1950, timeSinceEventHours: 2.5, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 0, productCategory: "anklet" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "First time visitor modest cart. Friendly checkout reminder.",
  },
  {
    id: 41,
    name: "HeldOut-RC1: Repeat Buyer Modest Ring Cart (2.2h)",
    category: "repeat_customer",
    input: { eventType: "cart_abandoned", cartTotal: 2600, timeSinceEventHours: 2.2, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 1, productCategory: "ring" },
    expectedAction: "remind_customer_to_checkout",
    expectedMaxDiscountPercent: 0,
    shouldAct: true,
    labelReasoning: "Repeat customer modest value. Standard checkout reminder.",
  },
  {
    id: 42,
    name: "HeldOut-RC2: Repeat Buyer Heavy Bracelet Cart (3.8h)",
    category: "repeat_customer",
    input: { eventType: "cart_abandoned", cartTotal: 5900, timeSinceEventHours: 3.8, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 3, productCategory: "bracelet" },
    expectedAction: "offer_discount",
    expectedMaxDiscountPercent: 10,
    shouldAct: true,
    labelReasoning: "3-time repeat buyer idle 3.8h on ₹5.9k bracelet cart. Discount appropriate.",
  },
  {
    id: 43,
    name: "HeldOut-TE1: Payment Failure Just 30 Mins Ago (0.5h)",
    category: "too_early",
    input: { eventType: "payment_failed", cartTotal: 3800, timeSinceEventHours: 0.5, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 1, productCategory: "chain" },
    expectedAction: "no_action",
    expectedMaxDiscountPercent: 0,
    shouldAct: false,
    labelReasoning: "Elapsed time 0.5h < 1.0h threshold. Must output no_action.",
  },
  {
    id: 44,
    name: "HeldOut-TE2: Cart Abandoned 40 Mins Ago (0.67h)",
    category: "too_early",
    input: { eventType: "cart_abandoned", cartTotal: 7100, timeSinceEventHours: 0.67, paymentAttemptStatus: "unpaid", customerPurchaseHistoryCount: 2, productCategory: "anklet" },
    expectedAction: "no_action",
    expectedMaxDiscountPercent: 0,
    shouldAct: false,
    labelReasoning: "Elapsed time 0.67h < 1.0h. Too early for recovery intervention.",
  },
  {
    id: 45,
    name: "HeldOut-CS1: Payment Failed + High Cart Value + Very Recent (0.3h)",
    category: "conflicting_signals",
    input: { eventType: "payment_failed", cartTotal: 9500, timeSinceEventHours: 0.3, paymentAttemptStatus: "failed", customerPurchaseHistoryCount: 2, productCategory: "anklet" },
    expectedAction: "no_action",
    expectedMaxDiscountPercent: 0,
    shouldAct: false,
    labelReasoning: "High value payment failure tempts immediate retry link, but 0.3h < 1h rule strictly forces no_action.",
  },
];
